# Generated by Django 5.0 on 2024-11-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_available', models.CharField(max_length=100, null=True)),
                ('trailer_name', models.CharField(max_length=100)),
                ('trailer_genre', models.CharField(max_length=100)),
                ('trailer_date', models.DateTimeField(auto_now=True)),
                ('watch_trailer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_payment', models.CharField(max_length=50)),
                ('cash_payment', models.CharField(max_length=50, null=True)),
                ('ticket_price_information', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FilmPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_information', models.CharField(max_length=100)),
                ('show_date', models.DateTimeField(auto_now=True)),
                ('theater_name', models.CharField(max_length=100)),
                ('order_ticket', models.CharField(max_length=50)),
                ('watch_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_film', to='onlinetheatre.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_quantity', models.IntegerField()),
                ('order_confirm_date', models.DateTimeField(auto_now=True)),
                ('theater_order_confirm', models.CharField(max_length=50)),
                ('name_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_user', to='onlinetheatre.user')),
                ('phone_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_of_user', to='onlinetheatre.user')),
            ],
        ),
    ]
